### ISSUE TITLE
Images haven't been updating for some time now

### ISSUE THREAD

**Issue by Jeydin21** [animemoeus/waifu-animemoeus#262]
I check on this website a few times when I'm bored and I've noticed that they've been staying the same for at least a month now

**Comment by animemoeus** [comment]
Yeah, so sorry for that 🥲

This happened after Elon takeover the Twitter, and he made the API request become paid.
![image](https://github.com/animemoeus/waifu-animemoeus/assets/33395829/dcfac1cb-3335-44f3-b8bd-3fd661efe3c8)

For the waifu database, I created a bot to periodically run to get data from Twitter.

And since I do not have access to Twitter API anymore, the bot can't get new waifu.

Actually, I already found some solution for this problem, will jump back into this issue later 😁👍

**Comment by Jeydin21** [comment]
Oh dang, I forgot about that. Looking forward to the solution 👀

**Comment by Jeydin21** [comment]
https://reddit.com/r/discordapp/s/HQJnxiGWUa

There might possibly be an issue with files on Discord now as well 😦

**Comment by animemoeus** [comment]
oh crap 🗿
